"use client";
import{useEffect,useMemo,useState}from"react";import{scheduleLabel}from"@/lib/schedule";
const ROMAN=["I","II","III","IV","V","VI","VII","VIII","IX","X","XI","XII"];
export default function Panel({lobbies,registrations,results,logs}:{lobbies:any[],registrations:any[],results:any[],logs:any[]}){
 const[t,setT]=useState("dash"),[m,setM]=useState(""),[liveLobby,setLiveLobby]=useState(lobbies[0]?.id||""),[liveMatch,setLiveMatch]=useState(1),[stageNo,setStageNo]=useState(1),[groupId,setGroupId]=useState(""),[teams,setTeams]=useState<any[]>([]),[board,setBoard]=useState<any[]>([]),[tour,setTour]=useState<any>(null),[tourLobby,setTourLobby]=useState(lobbies.find(x=>x.max_teams>12)?.id||lobbies[0]?.id||""),[saving,setSaving]=useState(false);
 const currentLobby=lobbies.find(x=>x.id===liveLobby),matchCount=Number(currentLobby?.match_count||6);
 const api=async(url:string,method="POST",body?:any)=>{const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok){setM(j.error||"Request failed");return null}location.reload();return j};
 async function out(){await fetch("/api/admin/logout",{method:"POST"});location.href="/admin/login"}
 async function loadLive(){if(!liveLobby)return;try{const q=new URLSearchParams({lobby_id:liveLobby});if(currentLobby?.max_teams>12){q.set("stage_no",String(stageNo));if(groupId){const g=tour?.groups?.find((x:any)=>x.id===groupId);if(g)q.set("group_no",String(g.group_no))}}const b=await fetch(`/api/admin/results?${q}`).then(r=>r.json());setBoard(Array.isArray(b)?b:[])}catch{setM("Could not load the live leaderboard")}}
 async function loadTour(id= tourLobby){if(!id)return;try{const r=await fetch(`/api/admin/lobbies/${id}`,{cache:"no-store"});const j=await r.json();if(r.ok){setTour(j);if(!stageNo&&j.stages?.[0])setStageNo(j.stages[0].stage_no);const gs=j.groups?.filter((g:any)=>g.stage_no===stageNo)||[];if(!groupId&&gs[0])setGroupId(gs[0].id)}}catch{setM("Could not load tournament control data")}}
 useEffect(()=>{if(t==="results")loadLive();const id=t==="results"?setInterval(loadLive,4000):undefined;return()=>{if(id)clearInterval(id as any)}},[t,liveLobby,stageNo,groupId]);
 useEffect(()=>{if(t==="tournament")loadTour();if(t==="results"&&currentLobby?.max_teams>12){setTourLobby(liveLobby);loadTour(liveLobby)}},[t,tourLobby,liveLobby]);
 useEffect(()=>{if(tour?.stages?.length&&!tour.stages.some((s:any)=>s.stage_no===stageNo))setStageNo(tour.stages[0].stage_no)},[tour]);
 useEffect(()=>{if(tour){const gs=tour.groups?.filter((g:any)=>g.stage_no===stageNo)||[];if(!gs.some((g:any)=>g.id===groupId))setGroupId(gs[0]?.id||"")}},[tour,stageNo]);
 const selectedGroup=tour?.groups?.find((g:any)=>g.id===groupId);
 const teamOptions=useMemo(()=>{if(currentLobby?.max_teams>12&&selectedGroup)return selectedGroup.teams||[];const src=teams.length?teams:registrations.filter(x=>x.lobby_id===liveLobby&&x.status!=="REJECTED");return [...new Map(src.map((x:any)=>[x.team_name,x])).values()].sort((a:any,b:any)=>a.team_name.localeCompare(b.team_name))},[teams,registrations,liveLobby,currentLobby,selectedGroup]);
 async function saveLive(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setM("");const d=Object.fromEntries(new FormData(e.currentTarget));const g=selectedGroup;const r=await fetch("/api/admin/results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lobby_id:liveLobby,team_name:d.team_name,stage_no:Number(stageNo),group_no:g?.group_no||1,group_id:g?.id||null,match_no:Number(liveMatch),placement:Number(d.placement),kills:Number(d.kills)})});const j=await r.json();setSaving(false);if(!r.ok){setM(j.error||"Could not save score");return}e.currentTarget.reset();await loadLive();}
 const multi=(x:any)=>Number(x?.max_teams||12)>12;
 return <main><nav className="nav"><div className="brand"><span className="mark">SF</span>ScrimForge <small>FREE FIRE ADMIN</small></div><div className="navlinks"><button onClick={()=>setT("dash")}>Dashboard</button><button onClick={()=>setT("lobbies")}>Scrims</button><button onClick={()=>setT("regs")}>Registrations</button><button onClick={()=>setT("results")}>Live Leaderboard</button><button onClick={()=>setT("tournament")}>Tournament Control</button><button onClick={()=>setT("logs")}>Logs</button><button onClick={out}>Logout</button></div></nav><section className="wrap page">{m&&<div className="notice danger">{m}</div>}
 {t==="dash"&&<><span className="eyebrow">FREE FIRE CONTROL CENTER</span><h1>Admin Dashboard</h1><div className="metrics"><div><small>SCRIM SESSIONS</small><b>{lobbies.length}</b></div><div><small>REGISTRATIONS</small><b>{registrations.length}</b></div><div><small>TOURNAMENTS</small><b>{lobbies.filter(x=>multi(x)).length}</b></div><div><small>MATCH RESULTS</small><b>{results.length}</b></div></div><div className="info"><h3>New tournament workflow</h3><p>Create an event with any number of slots. More than 12 teams automatically becomes a multi-group event. Groups hold up to 12 teams. Accept registrations → generate groups → enter group results → set how many teams qualify from each group → advance them into the next stage.</p></div></>}
 {t==="lobbies"&&<><span className="eyebrow">FREE FIRE EVENT MANAGEMENT</span><h1>Scrim Sessions</h1><Create api={api}/><List items={lobbies} render={(x:any)=><><div><b>{x.title}</b><small>{x.event_type==="TOURNAMENT"?"Tournament":"Scrim"} · Free Fire · {x.match_count||6} matches · {x.max_teams} slots {multi(x)?`· ${Math.ceil(x.max_teams/(x.group_size||12))} groups`:""} · {scheduleLabel(x)}</small></div><span className="tag">{x.status}</span>{multi(x)&&<button onClick={()=>{setTourLobby(x.id);setT("tournament")}}>Manage Tournament</button>}{x.status!=="CLOSED"&&x.status!=="COMPLETED"&&x.status!=="CANCELLED"&&<button onClick={()=>{if(confirm("Close this scrim? Registrations will stop."))api(`/api/admin/lobbies/${x.id}`,"PATCH",{status:"CLOSED"})}}>Close Scrim</button>}<button onClick={()=>{if(confirm("Delete this scrim permanently? Results and accepted teams will also be deleted."))api(`/api/admin/lobbies/${x.id}`,"DELETE")}}>Delete Scrim</button><button onClick={()=>api(`/api/admin/lobbies/${x.id}`,"PATCH",{room_id:prompt("Room ID")||null,room_password:prompt("Room Password")||null})}>Room</button></>}/></>}
 {t==="regs"&&<><span className="eyebrow">TEAM REGISTRATION MANAGEMENT</span><h1>Registrations</h1><p className="muted">Review submitted details, then accept or reject. For multi-group events, accepted teams are assigned to groups when you generate the stage.</p><List items={registrations.filter((x:any)=>x.status!=="CONFIRMED"&&x.status!=="REJECTED")} render={(x:any)=><><div><b>{x.team_name}</b><small>Captain: {x.player_name} · Contact: {x.whatsapp}</small><small>Reference: {x.code} · Scrim: {x.lobby_title||"Not assigned"}</small><small>Registered: {new Date(x.created_at).toLocaleString("en-IN")}</small></div><span className="tag">{x.status||"PENDING"}</span>{x.status!=="CONFIRMED"&&x.status!=="REJECTED"&&<><button onClick={()=>api(`/api/admin/registrations/${x.id}`,"PATCH",{status:"CONFIRMED"})}>Accept</button><button onClick={()=>{if(confirm("Reject this registration?"))api(`/api/admin/registrations/${x.id}`,"PATCH",{status:"REJECTED"})}}>Reject</button></>}</>}/></>}
 {t==="results"&&<><span className="eyebrow">LIVE FREE FIRE LEADERBOARD</span><h1>Live Leaderboard</h1><p className="muted">For a multi-group tournament, select the stage and group before entering scores. Standard 12-team scrims continue to work normally.</p><div className="form adminform"><div className="formgrid"><label>Event<select value={liveLobby} onChange={(e:any)=>{setLiveLobby(e.target.value);setLiveMatch(1);setStageNo(1);setGroupId("")}}>{lobbies.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>{multi(currentLobby)&&<label>Stage<select value={stageNo} onChange={(e:any)=>setStageNo(Number(e.target.value))}>{(tour?.lobby?.id===liveLobby?tour.stages:[]).map((s:any)=><option key={s.stage_no} value={s.stage_no}>Stage {s.stage_no} · {s.name}</option>)}</select></label>}{multi(currentLobby)&&<label>Group<select value={groupId} onChange={(e:any)=>setGroupId(e.target.value)}>{(tour?.lobby?.id===liveLobby?tour.groups.filter((g:any)=>g.stage_no===stageNo):[]).map((g:any)=><option key={g.id} value={g.id}>{g.name} · {g.teams.length} teams</option>)}</select></label>}<label>Match<select value={liveMatch} onChange={(e:any)=>setLiveMatch(Number(e.target.value))}>{Array.from({length:matchCount},(_,i)=>i+1).map(n=><option key={n} value={n}>Match {n}</option>)}</select></label></div><form onSubmit={saveLive}><div className="formgrid"><label>Team<select name="team_name" required>{teamOptions.map((x:any)=><option key={x.team_name} value={x.team_name}>{x.team_name}</option>)}</select></label><label>Placement<select name="placement" defaultValue="1">{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n} value={n}>{n===1?"1st — 12 pts":n===2?"2nd — 9 pts":n===3?"3rd — 8 pts":n===4?"4th — 7 pts":n===5?"5th — 6 pts":n===6?"6th — 5 pts":n===7?"7th — 4 pts":n===8?"8th — 3 pts":n===9?"9th — 2 pts":n===10?"10th — 1 pt":`${n}th — 0 pts`}</option>)}</select></label><label>Kills<input name="kills" type="number" min="0" defaultValue="0" required/></label></div><button className="btn primary" disabled={saving||!liveLobby}>{saving?"Saving...":"Save / Update Live Score"}</button></form></div><LiveBoard rows={board} matchCount={matchCount}/></>}
 {t==="tournament"&&<TournamentControl lobbies={lobbies} lobbyId={tourLobby} setLobbyId={setTourLobby} data={tour} reload={()=>loadTour(tourLobby)} api={api}/>} 
 {t==="logs"&&<><span className="eyebrow">AUDIT TRAIL</span><h1>Activity Logs</h1><List items={logs} render={(x:any)=><><div><b>{x.action}</b><small>{x.detail||""}</small></div><span className="muted">{new Date(x.created_at).toLocaleString("en-IN")}</span></>}/></>}</section></main>
}
function TournamentControl({lobbies,lobbyId,setLobbyId,data,reload,api}:{lobbies:any[],lobbyId:string,setLobbyId:(x:string)=>void,data:any,reload:()=>void,api:any}){
 const[qual,setQual]=useState(4),[nextMatches,setNextMatches]=useState(2),[nextGroups,setNextGroups]=useState(1),[nextSize,setNextSize]=useState(12),[nextName,setNextName]=useState(""),[nextMode,setNextMode]=useState("snake"),[qualMode,setQualMode]=useState("each_group"),[qualTotal,setQualTotal]=useState(6);
 const multi=lobbies.find(x=>x.id===lobbyId)?.max_teams>12;const stages=data?.stages||[];const groups=data?.groups||[];const stage=stages.find((s:any)=>s.stage_no===Number(data?.lobby?.current_stage||1))||stages[0];
 useEffect(()=>{if(stage){setQual(Number(stage.qualify_per_group||4));setNextMatches(Number(stage.match_count||2));setNextSize(Number(stage.group_size||12));setNextGroups(Math.max(1,Math.ceil(Number((data?.lobby?.max_teams)||12)/Number(stage.group_size||12))));}},[stage?.id]);
 if(!multi)return <div className="info"><h3>Tournament Control</h3><p>Select a multi-group event with more than 12 slots to use tournament stages.</p></div>;
 const currentStageGroups=stage?groups.filter((g:any)=>g.stage_id===stage.id):[];
 return <><span className="eyebrow">FLEXIBLE MULTI-GROUP TOURNAMENT ENGINE</span><h1>Tournament Control</h1><div className="form adminform"><label>Event<select value={lobbyId} onChange={e=>setLobbyId(e.target.value)}>{lobbies.filter((x:any)=>x.max_teams>12).map((x:any)=><option key={x.id} value={x.id}>{x.title} · {x.max_teams} slots</option>)}</select></label><div className="info"><b>Format is not hard-coded.</b> Group size, number of groups, qualification rule and next-stage distribution can change at every stage. A stage can feed its qualified teams into differently sized groups for the next stage.</div></div>
 {stages.map((s:any)=><section className="section" key={s.id}><div className="sectionHead"><div><span className="eyebrow">STAGE {s.stage_no}</span><h2>{s.name}</h2></div><span className="tag">{s.status}</span></div><div className="form adminform"><div className="formgrid"><label>Qualify from each group<input type="number" min="1" max="100" value={s.stage_no===stage?.stage_no?qual:s.qualify_per_group} onChange={e=>s.stage_no===stage?.stage_no&&setQual(Number(e.target.value))}/></label><label>Matches in this stage<input type="number" min="1" max="16" value={s.stage_no===stage?.stage_no?nextMatches:s.match_count} onChange={e=>s.stage_no===stage?.stage_no&&setNextMatches(Number(e.target.value))}/></label></div>
 {!groups.some((g:any)=>g.stage_id===s.id)&&<button className="btn primary" onClick={async()=>{await api(`/api/admin/lobbies/${lobbyId}`,"PATCH",{action:"generate_groups",stage_no:s.stage_no})}}>Generate Groups from Confirmed Teams</button>}
 {groups.filter((g:any)=>g.stage_id===s.id).map((g:any)=><div className="groupAdmin" key={g.id}><div className="sectionHead"><div><h3>{g.name}</h3><span className="muted">{g.teams.length}/{s.group_size||12} teams</span></div><span className="tag">{g.standings.length?`${g.standings[0]?.total_points||0} top points`:"No scores"}</span></div><div className="groupTeams">{g.teams.map((e:any,i:number)=><div key={e.id}><span>#{i+1}</span><b>{e.team_name}</b><small>{e.status}</small></div>)}</div>{g.standings.length>0&&<div className="miniStandings">{g.standings.slice(0,Math.min(g.teams.length,Number(s.qualify_per_group||qual))).map((r:any)=><span key={r.team_name}>✓ {r.team_name} · {r.total_points} pts</span>)}</div>}</div>)}
 {groups.some((g:any)=>g.stage_id===s.id)&&s.stage_no===stage?.stage_no&&<><div className="form adminform" style={{marginTop:16}}><h3>Next Stage Builder</h3><p className="muted">Choose exactly how the next stage should be formed. This is independent for every stage.</p><div className="formgrid"><label>Next stage name<input value={nextName} onChange={e=>setNextName(e.target.value)} placeholder={`Stage ${s.stage_no+1}`}/></label><label>Next stage matches<input type="number" min="1" max="16" value={nextMatches} onChange={e=>setNextMatches(Number(e.target.value))}/></label><label>Next stage groups<input type="number" min="1" max="100" value={nextGroups} onChange={e=>setNextGroups(Number(e.target.value))}/></label><label>Teams per next group<input type="number" min="1" max="100" value={nextSize} onChange={e=>setNextSize(Number(e.target.value))}/></label><label>How to select qualifiers<select value={qualMode} onChange={e=>setQualMode(e.target.value)}><option value="each_group">Top N from each group</option><option value="top_overall">Top N overall</option></select></label>{qualMode==="top_overall"?<label>Total qualifiers<input type="number" min="1" max="1000" value={qualTotal} onChange={e=>setQualTotal(Number(e.target.value))}/></label>:<label>Qualifiers per group<input type="number" min="1" max="100" value={qual} onChange={e=>setQual(Number(e.target.value))}/></label>}<label>Next-group distribution<select value={nextMode} onChange={e=>setNextMode(e.target.value)}><option value="snake">Balanced snake seeding</option><option value="balanced">Round-robin balanced</option><option value="random">Random</option></select></label></div><div className="notice">Example: 30 teams can be configured as <b>Top 6 overall</b> → one 6-team Final, while a separate next-stage configuration can be built from the remaining teams in a later update. Group size is not assumed to be the tournament size.</div><div className="actions"><button className="btn" onClick={async()=>{if(qualMode==="each_group"&&qual*currentStageGroups.length>nextGroups*nextSize){alert("The selected qualifiers do not fit into the next-stage capacity.");return}if(qualMode==="top_overall"&&qualTotal>nextGroups*nextSize){alert("The selected qualifiers do not fit into the next-stage capacity.");return}await api(`/api/admin/lobbies/${lobbyId}`,"PATCH",{action:"complete_stage",stage_no:s.stage_no})}}>Mark Stage {s.stage_no} Complete</button><button className="btn primary" onClick={async()=>{const j=await api(`/api/admin/lobbies/${lobbyId}`,"PATCH",{action:"advance_stage",stage_no:s.stage_no,qualify_per_group:qual,qualify_total:qualTotal,qualification_mode:qualMode,next_groups:nextGroups,next_group_size:nextSize,next_stage_name:nextName,next_match_count:nextMatches,next_distribution_mode:nextMode});if(j)reload()}}>Create Next Stage from Qualified Teams →</button></div></div></>}
 </div></section>)} </>}
function LiveBoard({rows,matchCount}:{rows:any[],matchCount:number}){return <div className="section"><div className="sectionHead"><div><span className="eyebrow">LIVE TOTALS</span><h2>Current Standings</h2></div><span className="muted">{matchCount} planned matches</span></div><div className="table"><div className="thead six"><span>Rank</span><span>Team</span><span>Booyahs</span><span>Placement</span><span>Kills</span><span>Total</span></div>{rows.length?rows.map((x:any,i:number)=><div className="trow six" key={x.team_name}><span><b>{ROMAN[i]||i+1}</b></span><strong>{x.team_name}</strong><span>{x.booyahs}</span><span>{x.placement_points}</span><span>{x.kill_points}</span><b>{x.total_points}</b></div>):<div className="empty">No scores entered yet.</div>}</div></div>}
function List({items,render}:{items:any[],render:(x:any)=>React.ReactNode}){return <div className="adminlist">{items.length?items.map(x=><div className="adminrow" key={x.id}>{render(x)}</div>):<div className="empty">Nothing here yet.</div>}</div>}
function Create({api}:{api:any}){const[scheduleMode,setScheduleMode]=useState("datetime"),[eventType,setEventType]=useState("SCRIM"),[maxTeams,setMaxTeams]=useState(12);const groups=Math.ceil(maxTeams/12);return <form className="form adminform" onSubmit={e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));api("/api/admin/lobbies","POST",{title:d.title,entry_fee:Number(d.entry_fee),prize_pool:Number(d.prize_pool),schedule_mode:d.schedule_mode,starts_at:d.starts_at,schedule_text:d.schedule_text,rules:d.rules,match_count:Number(d.match_count),max_teams:maxTeams,event_type:eventType})}}><h3>Create New Free Fire Event</h3><div className="notice">12 slots = normal single-lobby view. More than 12 = multi-group event, with 12 teams per group. {maxTeams>12&&<><b>{groups} starting groups</b> will be created for {maxTeams} slots; later stages can use different group counts and sizes.</>}</div><div className="formgrid"><label>Event Type<select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="SCRIM">Standard Scrim</option><option value="TOURNAMENT">Tournament</option></select></label><label>Total Team Slots<input name="max_teams" type="number" min="1" max="1000" step="1" value={maxTeams} onChange={e=>setMaxTeams(Number(e.target.value)||12)}/></label><label>Event Title<input name="title" required placeholder="Saturday Night Scrim / Forge Cup"/></label><label>Matches in first stage<input name="match_count" type="number" min="1" max="16" defaultValue="6"/></label><label>Entry Fee<input name="entry_fee" type="number" defaultValue="0"/></label><label>Prize Pool<input name="prize_pool" type="number" defaultValue="0"/></label><label>Schedule<select name="schedule_mode" value={scheduleMode} onChange={e=>setScheduleMode(e.target.value)}><option value="datetime">Set date &amp; time</option><option value="tbd">To be decided</option><option value="custom">I will type it myself</option></select></label>{scheduleMode==="datetime"&&<label>Start Date &amp; Time<input name="starts_at" type="datetime-local" required/></label>}{scheduleMode==="custom"&&<label>Schedule Text<input name="schedule_text" required placeholder="Date will be announced after slots are full"/></label>}</div><label>Rules / Notes<textarea name="rules" defaultValue="Free Fire squad event. For multi-group events, teams are divided into groups of up to 12 and qualification is controlled by admin."/></label><button className="btn primary">Create Free Fire Event</button></form>}
